package models

import "net/http"

// this file is generated by 'factor dev' but won't be overwritten. feel free to
// fill in your server implementation here!

var todoServer = NewTodoServer()

type TodoServer struct{}

func NewTodoServer() *TodoServer {
	return &TodoServer{}
}

func (srv *TodoServer) Get(r *http.Request, req *GetTodoReq, res *GetTodoRes) error {
	// TODO

	res.Data.ID = req.ID
	res.Data.Description = "Do Something"
	res.Data.Name = "MY TASK"
	return nil
}
