package models

// this file is generated by 'factor dev' but won't be overwritten. feel free to
// fill in your own client logic here!

import (
	"bytes"
	"log"
	"net/http"

	"github.com/gorilla/rpc/v2/json"
	"github.com/satori/go.uuid"
)

type TodoClient struct {
}

func (cl *TodoClient) Get(id uuid.UUID) (*Todo, error) {
	url := "http://localhost:3000/rpc"
	req := GetTodoReq{ID: id}
	var res GetTodoRes
	message, err := json.EncodeClientRequest("TodoServer.Get", req)
	if err != nil {
		log.Fatalf("%s", err)
	}
	rq, err := http.NewRequest("POST", url, bytes.NewBuffer(message))
	if err != nil {
		log.Fatalf("%s", err)
	}
	rq.Header.Set("Content-Type", "application/json")
	client := new(http.Client)
	resp, err := client.Do(rq)
	if err != nil {
		log.Fatalf("Error in sending request to %s. %s", url, err)
	}
	defer resp.Body.Close()
	err = json.DecodeClientResponse(resp.Body, &res)
	if err != nil {
		log.Fatalf("Couldn't decode response. %s", err)
	}
	return &res.Data, nil
}

// TODO: more
