package models

// this file is generated by 'factor dev' but won't be overwritten. feel free to
// fill in your server implementation here!

import (
	"net/http"
)

var todoServer = NewTodoServer()

type TodoServer struct{}

func NewTodoServer() *TodoServer {
	return &TodoServer{}
}

func (srv *TodoServer) Create(req CreateTodoReq, res *CreateTodoRes) error {
	// TODO
	return nil
}

func (srv *TodoServer) Get(r *http.Request, req *GetTodoReq, res *GetTodoRes) error {
	res.Data = Todo{
		ID:          req.ID,
		Name:        "Todo Name",
		Description: "Todo Description",
		Permalink:   "/todos/" + req.ID.String(),
	}
	return nil
}

func (srv *TodoServer) Update(req UpdateTodoReq, res *UpdateTodoRes) error {
	// TODO
	return nil
}

func (srv *TodoServer) Delete(req DeleteTodoReq, res *DeleteTodoRes) error {
	// TODO
	return nil
}
