package models

// this file is generated by 'factor dev' but won't be overwritten. feel free to
// fill in your own client logic here!

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/gorilla/rpc/v2/json"
	"github.com/satori/go.uuid"
)

type TodoClient struct {
}

func (cl *TodoClient) Get(id uuid.UUID) (*Todo, error) {

	url := "http://localhost:3000/rpc"
	args := &GetTodoReq{
		ID: id,
	}
	message, err := json.EncodeClientRequest("TodoServer.Get", args)

	//message, err := json.EncodeClientRequest("TodoServer.Get", nil)
	if err != nil {
		log.Fatalf("%s", err)
	}
	fmt.Println(string(message))
	//req, err := http.NewRequest("POST", url, nil)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(message))
	if err != nil {
		log.Fatalf("%s", err)
	}
	req.Header.Set("Content-Type", "application/json")
	client := http.DefaultClient
	resp, err := client.Do(req)
	if err != nil {
		log.Fatalf("Error in sending request to %s. %s", url, err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	fmt.Println(string(body), err)
	var result GetTodoRes
	bb := bytes.NewBuffer(body)
	err = json.DecodeClientResponse(bb, &result)
	if err != nil {
		log.Fatalf("Couldn't decode response. %s", err)
	}
	return &result.Data, err
}

// TODO: more
