package models

// this file is generated by 'factor dev' but won't be overwritten. feel free
// to make any modifications you want in here. If you do, make sure to
// check TodoServer and TodoClient because you might need to
// update them too so the thing still builds.

import (
	"context"
	
	"github.com/satori/go.uuid"
)

type CreateTodoReq struct {
	Ctx context.Context
	Data Todo
}

type CreateTodoRes struct {
	Err error
}

type GetTodoReq struct {
	ID uuid.UUID
}

type GetTodoRes struct {
	Data Todo
}

type UpdateTodoReq struct {
	ID uuid.UUID
	New Todo
}

type UpdateTodoRes struct {
	Err error
}

type DeleteTodoReq struct {
	ID uuid.UUID
}

type DeleteTodoRes struct {
	Err error
}
