package models

// this file is generated by 'factor dev' but won't be overwritten. feel free to
// fill in your own client logic here!

import (
	"net/rpc"

	"github.com/satori/go.uuid"
)

type TodoClient struct{
	RPC *rpc.Client
}

func (cl *TodoClient) Get(id uuid.UUID) (*Todo, error) {
	req := GetTodoReq{ID: id}
	var res GetTodoRes
	if err := cl.RPC.Call("Todo.Get", req, &res); err != nil {
		return nil, err
	}
	return &res.Data, nil
}

// TODO: more
