package models

import (
	"context"

	"github.com/satori/go.uuid"
)

// this file should be generated by factor

// TodoClient is a wrapper around net/rpc to make calls to the rpc server.
//
// use NewTodoClient to create one of these
type TodoClient struct{}

// NewTodoClient creates a new TodoClient
func NewTodoClient() TodoClient {
	return TodoClient{}
}

// NewTodo is a Todo that is being created
type NewTodo struct {
	Ctx         context.Context
	ID          uuid.UUID
	Name        string
	Description string
}

// TodoResp has some kind of error or status thing in it. Maybe this?
type TodoResp struct {
	Result error
}
