package components

import (
	"github.com/bketelsen/factor/markup"
)

// App is the top level object in the rendered markup. Call NewApp to create this
type App struct {
	Greeting string
	Sub      markup.Componer
}

// NewApp creates a new App component
//
// this function should be autogenerated
func NewApp(greeting string) *App {
	return &App{
		Greeting: greeting,
		Sub:      NewNav(),
	}
}

func (a *App) OnClick(v string) string {
	a.Greeting = "blog!"
	return a.Render()
}
