package components

import (
	"github.com/bketelsen/factor/markup"
)

type Nav struct {
	MyProp      string
	CurrentPath string
}

// This should be autogenerated
func NewNav() *Nav {
	return &Nav{}
}

func (n *Nav) OnAfterPrint(e *markup.Event) {

}
